name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.14"

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --dev

      - name: Run Type Checks
        run: uv run ty check

      - name: Check Formatting
        run: uv run ruff format --check

      - name: Run Linting
        run: uv run ruff check

      - name: Run Unit Tests
        run: uv run pytest

      - name: Build Package
        run: uv run python -m build